In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
match=pd.read_csv("matches.csv")
delivery=pd.read_csv("deliveries.csv")

In [3]:
match.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [5]:
match.shape

(756, 18)

In [6]:
delivery.shape

(179078, 21)

In [7]:
delivery.groupby(["match_id","inning"]).sum()["total_runs"].reset_index()

      match_id  inning  total_runs
0            1       1         207
1            1       2         172
2            2       1         184
3            2       2         187
4            3       1         183
...        ...     ...         ...
1523     11413       2         170
1524     11414       1         155
1525     11414       2         162
1526     11415       1         152
1527     11415       2         157

[1528 rows x 3 columns]

In [8]:
total_score_df=delivery.groupby(["match_id","inning"]).sum()["total_runs"].reset_index()
total_score_df[total_score_df["inning"]==1]

      match_id  inning  total_runs
0            1       1         207
2            2       1         184
4            3       1         183
6            4       1         163
8            5       1         157
...        ...     ...         ...
1518     11347       1         143
1520     11412       1         136
1522     11413       1         171
1524     11414       1         155
1526     11415       1         152

[756 rows x 3 columns]

In [9]:
total_score_df=total_score_df[total_score_df["inning"]==1]

In [10]:
match_df=match.merge(total_score_df[["match_id","total_runs"]],left_on="id",right_on="match_id")

In [11]:
match_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,184
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,183
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,163
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157

In [12]:
match_df["team1"].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [13]:
team=['Sunrisers Hyderabad',
      'Mumbai Indians',
      'Royal Challengers Bangalore',
      'Kolkata Knight Riders',
      'Kings XI Punjab',
      'Chennai Super Kings',
      'Rajasthan Royals',
      'Delhi Capitals']

In [14]:
match_df["team1"]=match_df["team1"].str.replace("Delhi Daredevils","Delhi Capitals")
match_df["team1"]=match_df["team2"].str.replace("Delhi Daredevils","Delhi Capitals")
match_df["team1"]=match_df["team1"].str.replace("Deccan Chargers","Sunrisers Hyderabad")
match_df["team1"]=match_df["team2"].str.replace("Deccan Chargers","Sunrisers Hyderabad")

In [15]:
match_df=match_df[match_df["team1"].isin(team)]
match_df=match_df[match_df["team2"].isin(team)]

In [16]:
match_df.shape

(571, 20)

In [17]:
match_df["dl_applied"].value_counts()

dl_applied
0    557
1     14
Name: count, dtype: int64

In [18]:
match_df=match_df[match_df["dl_applied"]==0]

In [19]:
match_df=match_df[["match_id","city","winner","total_runs"]]

In [20]:
match_df

     match_id           city                 winner  total_runs
0           1      Hyderabad    Sunrisers Hyderabad         207
2           3         Rajkot  Kolkata Knight Riders         183
3           4         Indore        Kings XI Punjab         163
5           6      Hyderabad    Sunrisers Hyderabad         135
6           7         Mumbai         Mumbai Indians         178
..        ...            ...                    ...         ...
751     11347         Mumbai         Mumbai Indians         143
752     11412        Chennai         Mumbai Indians         136
753     11413  Visakhapatnam         Delhi Capitals         171
754     11414  Visakhapatnam    Chennai Super Kings         155
755     11415      Hyderabad         Mumbai Indians         152

[557 rows x 4 columns]

In [21]:
delivery_df=match_df.merge(delivery,on="match_id")

In [22]:
delivery_df[delivery_df['inning']==2].head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [23]:
delivery_df=delivery_df[delivery_df["inning"]==2]

In [24]:
delivery_df.shape

(64433, 24)

In [25]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64433 entries, 125 to 133058
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          64433 non-null  int64
 1   city              63844 non-null  object
 2   winner            64406 non-null  object
 3   total_runs_x      64433 non-null  int64
 4   inning            64433 non-null  int64
 5   batting_team      64433 non-null  object
 6   bowling_team      64433 non-null  object
 7   over              64433 non-null  int64
 8   ball              64433 non-null  int64
 9   batsman           64433 non-null  object
 10  non_striker       64433 non-null  object
 11  bowler            64433 non-null  object
 12  is_super_over     64433 non-null  int64
 13  wide_runs         64433 non-null  int64
 14  bye_runs          64433 non-null  int64
 15  legbye_runs       64433 non-null  int64
 16  noball_runs       64433 non-null  int64
 17  penalty_runs      64433 non-null  int64
 18  batsman_runs      64433 non-null  int64
 19  extra_runs        64433 non-null  int64
 20  total_runs_y      64433 non-null  int64
 21  player_dismissed  3089 non-null   object
 22  dismissal_kind    3089 non-null   object
 23  fielder           2216 non-null   object
dtypes: int64(14), object(10)
memory usage: 12.3+ MB

In [26]:
delivery_df.isnull().sum()

match_id                0
city                  589
winner                 27
total_runs_x            0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
batsman                 0
non_striker             0
bowler                  0
is_super_over           0
wide_runs               0
bye_runs                0
legbye_runs             0
noball_runs             0
penalty_runs            0
batsman_runs            0
extra_runs              0
total_runs_y            0
player_dismissed    61344
dismissal_kind      61344
fielder             62217
dtype: int64

In [27]:
delivery_df["currect_score"]=delivery_df.groupby("match_id")["total_runs_y"].cumsum()

In [28]:
delivery_df[delivery_df["match_id"]==1].head(60)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,currect_score
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,1
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,2,0,2,NaN,NaN,NaN,3
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,7
130,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,11
131,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,11
132,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,11
133,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,12
134,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,12
135,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,12
136,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,12
137,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,12
138,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,...,0,0,0,4,0,4,NaN,NaN,NaN,16
139,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,17
140,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,21
141,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,...,0,0,0,1,0,1,NaN,NaN,NaN,22
142,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,...,0,0,0,6,0,6,NaN,NaN,NaN,28
143,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,...,0,0,0,1,0,1,NaN,NaN,NaN,29
144,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,...,0,0,0,6,0,6,NaN,NaN,NaN,35
145,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,...,0,0,0,2,0,2,NaN,NaN,NaN,37
146,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,...,0,0,0,0,1,1,NaN,NaN,NaN,38
147,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,38
148,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,39
149,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,43
150,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,43
151,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,43
152,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,43
153,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,...,0,0,0,0,1,1,NaN,NaN,NaN,44
154,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,44
155,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,6,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,44
156,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,7,CH Gayle,...,0,0,0,4,0,4,NaN,NaN,NaN,48
157,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,1,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,48
158,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,2,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,52
159,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,3,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,52
160,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,4,Mandeep Singh,...,0,0,0,0,0,0,Mandeep Singh,bowled,NaN,52
161,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,5,TM Head,...,0,0,0,2,0,2,NaN,NaN,NaN,54
162,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,6,TM Head,...,0,0,0,0,0,0,NaN,NaN,NaN,54
163,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,1,CH Gayle,...,0,0,0,0,0,0,NaN,NaN,NaN,54
164,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,2,CH Gayle,...,0,0,0,6,0,6,NaN,NaN,NaN,60
165,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,3,CH Gayle,...,0,0,0,0,0,0,CH Gayle,caught,DA Warner,60
166,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,4,TM Head,...,0,0,0,0,0,0,NaN,NaN,NaN,60
167,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,5,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,61
168,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,6,KM Jadhav,...,0,0,0,0,0,0,NaN,NaN,NaN,61
169,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,1,TM Head,...,0,0,0,4,0,4,NaN,NaN,NaN,65
170,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,2,TM Head,...,0,0,0,2,0,2,NaN,NaN,NaN,67
171,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,3,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,68
172,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,4,KM Jadhav,...,0,0,0,1,0,1,NaN,NaN,NaN,69
173,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,5,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,70
174,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,6,KM Jadhav,...,0,0,0,4,0,4,NaN,NaN,NaN,74
175,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,1,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,75
176,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,2,KM Jadhav,...,0,0,0,0,1,1,NaN,NaN,NaN,76
177,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,3,KM Jadhav,...,0,0,0,0,0,0,NaN,NaN,NaN,76
178,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,4,KM Jadhav,...,0,0,0,1,0,1,NaN,NaN,NaN,77
179,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,5,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,78
180,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,6,KM Jadhav,...,0,0,0,6,0,6,NaN,NaN,NaN,84
181,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,9,7,KM Jadhav,...,0,0,0,1,0,1,NaN,NaN,NaN,85
182,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,1,KM Jadhav,...,0,1,0,1,1,2,NaN,NaN,NaN,87
183,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,2,TM Head,...,0,0,0,4,0,4,NaN,NaN,NaN,91
184,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,3,TM Head,...,0,0,0,1,0,1,NaN,NaN,NaN,92

In [29]:
delivery_df["run_left"]=delivery_df["total_runs_x"]-delivery_df["currect_score"]

In [30]:
delivery_df["ball_left"]=120-((delivery_df["over"]-1)*6+delivery_df["ball"])

In [31]:
delivery_df["player_dismissed"]=delivery_df["player_dismissed"].fillna("0")
delivery_df["player_dismissed"]=delivery_df["player_dismissed"].apply(lambda x:0 if x=="0" else 1)
delivery_df["player_dismissed"]=delivery_df["player_dismissed"].astype(int)

In [32]:
delivery_df["wicket"]=delivery_df.groupby("match_id")["player_dismissed"].cumsum().values

In [33]:
delivery_df["player_dismissed"].value_counts()

player_dismissed
0    61344
1     3089
Name: count, dtype: int64

In [34]:
delivery_df["remaing_wicket"]=10-delivery_df["wicket"]

In [35]:
delivery_df["crr"]=(delivery_df["currect_score"]/(120-delivery_df["ball_left"]))*6

In [36]:
delivery_df["rrr"]=(delivery_df["run_left"]/(delivery_df["ball_left"]))*6

In [37]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,player_dismissed,dismissal_kind,fielder,currect_score,run_left,ball_left,wicket,remaing_wicket,crr,rrr
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,NaN,NaN,1,206,119,0,10,6.000000,10.386555
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,1,206,118,0,10,3.000000,10.474576
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,1,206,117,0,10,2.000000,10.564103
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,NaN,NaN,3,204,116,0,10,4.500000,10.551724
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,NaN,NaN,7,200,115,0,10,8.400000,10.434783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133054,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,NaN,NaN,152,0,4,5,5,7.862069,0.000000
133055,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,NaN,NaN,154,-2,3,5,5,7.897436,-4.000000
133056,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,run out,KH Pandya,155,-3,2,6,4,7.881356,-9.000000
133057,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,NaN,NaN,157,-5,1,6,4,7.915966,-30.000000
133058,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,1,lbw,NaN,157,-5,0,7,3,7.850000,-inf

In [38]:
def result(row):
   return 1 if row["batting_team"]==row["winner"] else 0

In [39]:
delivery_df["result"]=delivery_df.apply(result,axis=1)

In [40]:
delivery_df.head(1)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,dismissal_kind,fielder,currect_score,run_left,ball_left,wicket,remaing_wicket,crr,rrr,result
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,NaN,NaN,1,206,119,0,10,6.0,10.386555,0

In [41]:
delivery_df.isna().sum()

match_id                0
city                  589
winner                 27
total_runs_x            0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
batsman                 0
non_striker             0
bowler                  0
is_super_over           0
wide_runs               0
bye_runs                0
legbye_runs             0
noball_runs             0
penalty_runs            0
batsman_runs            0
extra_runs              0
total_runs_y            0
player_dismissed        0
dismissal_kind      61344
fielder             62217
currect_score           0
run_left                0
ball_left               0
wicket                  0
remaing_wicket          0
crr                     0
rrr                     8
result                  0
dtype: int64

In [42]:
delivery_df["city"].fillna(method="backfill",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_14260\3270049102.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  delivery_df["city"].fillna(method="backfill",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_14260\3270049102.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  delivery_df["city"].fillna(method="backfill",inplace=True)

In [43]:
final_df=delivery_df[["batting_team","bowling_team","city","currect_score","run_left","ball_left","remaing_wicket","total_runs_x","crr",'rrr','result']]

In [44]:
final_df.dropna(inplace=True)
final_df.isnull().sum()
#final_df

C:\Users\Admin\AppData\Local\Temp\ipykernel_14260\556359280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

batting_team      0
bowling_team      0
city              0
currect_score     0
run_left          0
ball_left         0
remaing_wicket    0
total_runs_x      0
crr               0
rrr               0
result            0
dtype: int64

In [45]:
final_df=final_df.sample(final_df.shape[0])

In [46]:
final_df.sample(3)

,batting_team,bowling_team,city,currect_score,run_left,ball_left,remaing_wicket,total_runs_x,crr,rrr,result
10808,Chennai Super Kings,Kolkata Knight Riders,Chennai,1,146,116,10,147,1.500000,7.551724,1
82989,Kings XI Punjab,Delhi Daredevils,Delhi,84,80,74,9,164,10.956522,6.486486,1
108087,Royal Challengers Bangalore,Rajasthan Royals,Bengaluru,173,58,14,5,231,9.792453,24.857143,0

In [47]:
final_df.shape

(64425, 11)

In [48]:
final_df.dropna(inplace=True)

In [49]:
final_df=final_df[final_df["ball_left"]!=0]

In [50]:
final_df.shape

(64229, 11)

In [51]:
x=final_df.iloc[:,:-1]
y=final_df["result"]

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [140]:
step2=LogisticRegression(solver="liblinear")

In [142]:
step1=ColumnTransformer([('trf',OneHotEncoder(sparse_output=False,drop="first"),["batting_team","bowling_team","city"])],remainder="passthrough")

In [144]:
pipe=Pipeline([("step1",step1),
             ("step2",step2)])

In [146]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [148]:
y_pred=pipe.predict(x_test)

In [152]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8115366651097617

In [154]:
pipe.predict_proba(x_test)[0]

array([0.68424573, 0.31575427])

In [60]:
import pickle
pickle.dump(pipe,open('pipe.pkl', 'wb'))

In [61]:
# using random forest algoritmn

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
step2=RandomForestClassifier()

In [64]:
pipe=Pipeline([("step1",step1),
             ("step2",step2)])

In [65]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', RandomForestClassifier())])

In [66]:
y_pred=pipe.predict(x_test)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9983652498832322

In [68]:
pipe.predict_proba(x_test)[0]

array([0.98, 0.02])

In [156]:
final_df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Kings XI Punjab',
       'Chennai Super Kings', 'Delhi Capitals', 'Sunrisers Hyderabad'],
      dtype=object)

In [158]:
final_df['city'].unique()

array(['Delhi', 'Kolkata', 'Ahmedabad', 'Jaipur', 'Bengaluru',
       'Visakhapatnam', 'Hyderabad', 'Indore', 'Mumbai', 'Ranchi',
       'Durban', 'Chandigarh', 'Pune', 'Chennai', 'Bangalore', 'Mohali',
       'Port Elizabeth', 'East London', 'Bloemfontein', 'Rajkot', 'Kochi',
       'Sharjah', 'Johannesburg', 'Dharamsala', 'Abu Dhabi', 'Cape Town',
       'Cuttack', 'Centurion', 'Nagpur', 'Kanpur', 'Kimberley', 'Raipur'],
      dtype=object)